### ISSUE TITLE
The error when I run python /tools/demo.py --no-gpu ?

### ISSUE THREAD

**Issue by yingning** [tianzhi0549/CTPN#53]
ImportError: No module named layers.text_proposal_layer
Traceback (most recent call last):
  File "/home/jsj/pycharm-2017.1.4/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jsj/pycharm-2017.1.4/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jsj/CTPN/tools/demo.py", line 42, in <module>
    text_proposals_detector=TextProposalDetector(CaffeModel(NET_DEF_FILE, MODEL_FILE))
  File "/home/jsj/CTPN/tools/other.py", line 87, in __init__
    self.net=caffe.Net(net_def_file, model_file, caffe.TEST)
SystemError: NULL result without error in PyObject_Call

Process finished with exit code 1

@tianzhi0549 I got the above error ,I need your help ,thanks in advance!

**Comment by tianzhi0549** [comment]
@yingning I don't know why you have this error. But please try to run `export PYTHONPATH=src/:$PYTHONPATH` before `python tools/demo.py` in the same working directory. Thank you.

**Comment by yingning** [comment]
Thank you very much ,your advice solved my problem! @tianzhi0549

**Comment by guptasaurabh9868** [comment]
I am also getting the same error. what is this PYTHONPATH variable?  I tried appending ```src/``` to ```PYTHONPATH``` variable as well as my ```PATH``` variable. But no success. Please help asap. Thanks in advance.
