### ISSUE TITLE
No module named cpu_nms

### ISSUE THREAD

**Issue by andy-listen** [tianzhi0549/CTPN#57]
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from ctpnport import *
  File "/mnt/sceneReco/ctpnport.py", line 29, in <module>
    from detectors import TextProposalDetector, TextDetector
  File "./CTPN/src/detectors.py", line 4, in <module>
    from utils.cpu_nms import cpu_nms as nms
ImportError: No module named cpu_nms

**Comment by tianzhi0549** [comment]
@andy-listen Please add the directory of `cpu_nms.so` to your PYTHONPATH. For example, you can run `export PYTHONPATH=$PYTHONPATH:<replace this with the directory of cpu_nms.so>` before running your code.

**Comment by Clare-Meng** [comment]
@tianzhi0549 
python tools/demo.py --no-gpu
Traceback (most recent call last):
  File "tools/demo.py", line 31, in <module>
    from detectors import TextProposalDetector, TextDetector
  File "./src/detectors.py", line 4, in <module>
    from utils.cpu_nms import cpu_nms as nms
ImportError: No module named cpu_nms

I am getting the same error when running in CPU only mode. I can't seem to find the cpu_nms.so file. I can only find the cpu_nms.pyx file and have tried exporting the pythonpath but am still getting the same error.

**Comment by szbach** [comment]
so any upates? i got the same error...

**Comment by szbach** [comment]
i just solve the issue according to the link (https://github.com/bear63/sceneReco/issues/15). but i got a new error as follows:
Traceback (most recent call last):
  File "/home/benson/projects/sceneReco/demo.py", line 2, in <module>
    from ctpnport import *
  File "/home/benson/projects/sceneReco/ctpnport.py", line 29, in <module>
    from detectors import TextProposalDetector, TextDetector
  File "/home/benson/projects/sceneReco/CTPN/src/detectors.py", line 1, in <module>
    from cfg import Config as cfg
ImportError: No module named cfg

@tianzhi0549 Any advice? thanks.

**Comment by mionyu** [comment]
@szbach I bet you forgot to do a make in main directory

**Comment by szbach** [comment]
@mionyu yes, just ignore it...but i got another error message:
Traceback (most recent call last):
  File "tools/demo.py", line 24, in <module>
    from detectors import TextProposalDetector, TextDetector
  File "./src/detectors.py", line 4, in <module>
    from utils.cpu_nms import cpu_nms as nms
ImportError: ./src/utils/cpu_nms.so: undefined symbol: PyFPE_jbuf

**Comment by idefix92** [comment]
@szbach ypu have an issue with numpy. probably you are running anaconda? Remove anaconda and try again. it will work. If you don't want to remove anaconda seek for another solution :)

**Comment by yhyaaln** [comment]
I add the directory of cpu_nms.so to  PYTHONPATH,but still prompting the error: 
Traceback (most recent call last):
File "tools/demo.py", line 31, in 
from detectors import TextProposalDetector, TextDetector
File "./src/detectors.py", line 4, in 
from utils.cpu_nms import cpu_nms as nms
ImportError: No module named cpu_nms

How can I solve it? Thank you. @tianzhi0549

**Comment by JanSword** [comment]
add
import pyximport  
pyximport.install()
to detectors.py
if you can't import pyximport,please pip install Cython
